apiVersion: v1
kind: Secret

metadata:
  name: self-service-portal-secret
  namespace: ssp
  labels:
    app.kubernetes.io/name: self-service-portal

type: Opaque
stringData:
  SECRET_KEY: "c106aef9ba6cd8b5e93be28bbd7849c9c252fa58b9639a4580669c7b2389640b"
  ADMIN_PASSWORD: "Admin@12345"
  # DATABASE_USER: "postgres"
  # DATABASE_PASSWORD: "madhu123"
  # JWT_SECRET: "change-me"
  SMTP_PASSWORD: ""
